TRUNCATE TABLE  identityplatform.permissions,
                identityplatform.resolution_domains,
                identityplatform.role_assignments,
                identityplatform.roles,
                inboxmanagement.inbox_group_assignments,
                inboxmanagement.downtime,
                inboxmanagement.inbox_groups,
                inboxmanagement.inboxes,
                journeymanagement.edges,
                journeymanagement.nodes,
                journeymanagement.inbox_group_endpoints,
                journeymanagement.journeys,
                identityplatform.users,
                identityplatform.tenants
RESTART IDENTITY;