package com.inmotionchat.core.audit;

public enum AuditAction {

    CREATE_TENANT,

    CREATE_ROLE,
    UPDATE_ROLE,
    DELETE_ROLE,
    ASSIGN_ROLE,

    UPDATE_JOURNEY_GRAPH,

    CREATE_INBOX,

    CREATE_INBOX_GROUP,
    UPDATE_INBOX_GROUP,
    DELETE_INBOX_GROUP,
    ASSIGN_INBOXES,
    REMOVE_INBOX_ASSIGNMENT,

    CREATE_CHATBOX,
    UPDATE_CHATBOX,
    DELETE_CHATBOX,

    CREATE_JOURNEY,
    UPDATE_JOURNEY,
    DELETE_JOURNEY

}
